# Generated by Django 4.1.4 on 2023-01-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
