# Generated by Django 4.1.4 on 2023-02-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SanApp', '0005_alter_avatar_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
