# Generated by Django 4.1.4 on 2023-02-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SanApp', '0006_delete_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=248)),
            ],
        ),
    ]
